import type { AdminModuleConfig } from "@/types/admin";

const statusOptions = [
  { label: "Draft", value: "draft" },
  { label: "Review", value: "review" },
  { label: "Published", value: "published" },
];

export const adminModules: Record<string, AdminModuleConfig> = {
  pages: {
    title: "Pages",
    table: "pages",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "template_type", label: "Template Type", type: "text", required: true },
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  practice_areas: {
    title: "Practice Areas",
    table: "practice_areas",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  industry_solutions: {
    title: "Industry Solutions",
    table: "industry_solutions",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  publications: {
    title: "Publications",
    table: "publications",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  careers: {
    title: "Careers",
    table: "careers",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  offices: {
    title: "Offices",
    table: "offices",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  locations: {
    title: "Locations",
    table: "locations",
    primaryLabel: "city",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "city", label: "City", type: "text", required: true },
      { key: "office_name", label: "Office Name", type: "text", required: true },
      { key: "address", label: "Address", type: "textarea", required: true },
      { key: "phone", label: "Phone", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "map_url", label: "Map URL", type: "text" },
      { key: "contact_person", label: "Contact Person", type: "text" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  team_members: {
    title: "Employee Management",
    table: "team_members",
    primaryLabel: "name",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "designation", label: "Designation", type: "text", required: true },
      { key: "location", label: "Where They Are From", type: "text" },
      { key: "linkedin_url", label: "LinkedIn Profile", type: "text" },
      { key: "photo_url", label: "Photo URL", type: "text" },
      { key: "credentials", label: "Credentials", type: "text" },
      { key: "bio", label: "About", type: "textarea" },
      { key: "display_order", label: "Display Order", type: "number" },
      { key: "featured", label: "Featured", type: "checkbox" },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  insight_categories: {
    title: "Insight Categories",
    table: "insight_categories",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "display_order", label: "Display Order", type: "number" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  insight_tags: {
    title: "Insight Tags",
    table: "insight_tags",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  menu_items: {
    title: "Mega Menu",
    table: "menu_items",
    primaryLabel: "label",
    fields: [
      { key: "label", label: "Label", type: "text", required: true },
      { key: "href", label: "Href", type: "text", required: true },
      { key: "group_name", label: "Group", type: "text", required: true },
      { key: "display_order", label: "Display Order", type: "number" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
    ],
  },
  site_settings: {
    title: "Global Settings",
    table: "site_settings",
    primaryLabel: "brand_name",
    fields: [
      { key: "brand_name", label: "Brand Name", type: "text", required: true },
      { key: "logo_url", label: "Logo URL", type: "text" },
      { key: "primary_email", label: "Primary Email", type: "text" },
      { key: "primary_phone", label: "Primary Phone", type: "text" },
      { key: "footer_text", label: "Footer Text", type: "textarea" },
      { key: "disclaimers", label: "Disclaimers", type: "textarea" },
    ],
  },
};
