import type { AdminModuleConfig } from "@/types/admin";

const statusOptions = [
  { label: "Draft", value: "draft" },
  { label: "Review", value: "review" },
  { label: "Published", value: "published" },
];

export const adminModules: Record<string, AdminModuleConfig> = {
  pages: {
    title: "Pages",
    table: "pages",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "template_type", label: "Template Type", type: "text", required: true, section: "Basics" },
      { key: "excerpt", label: "Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  practice_areas: {
    title: "Practice Areas",
    table: "practice_areas",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  industry_solutions: {
    title: "Industry Solutions",
    table: "industry_solutions",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  publications: {
    title: "Insights",
    table: "publications",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "image_url", label: "Feature Image URL", type: "text", section: "Media" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "excerpt", label: "Card Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  careers: {
    title: "Careers / Join Us",
    table: "careers",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "excerpt", label: "Listing Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "location", label: "Location", type: "text", section: "Job Details", placeholder: "Ahmedabad / Remote / Hybrid" },
      { key: "job_type", label: "Job Type", type: "text", section: "Job Details", placeholder: "Full-time / Internship" },
      { key: "experience", label: "Experience", type: "text", section: "Job Details", placeholder: "0-2 years" },
      { key: "department", label: "Department", type: "text", section: "Job Details", placeholder: "Audit / Tax / Advisory" },
      { key: "application_deadline", label: "Application Deadline", type: "text", section: "Job Details", placeholder: "30 June 2026" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  offices: {
    title: "Offices",
    table: "offices",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  locations: {
    title: "Locations",
    table: "locations",
    primaryLabel: "city",
    listColumns: [
      { key: "city", label: "Branch" },
      { key: "address", label: "Address" },
      { key: "display_order", label: "Priority" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Branch Basics" },
      { key: "city", label: "Branch Location", type: "text", required: true, section: "Branch Basics" },
      { key: "office_name", label: "Office Name", type: "text", section: "Branch Basics", placeholder: "Optional" },
      { key: "contact_person", label: "Contact Person", type: "text", section: "Branch Basics" },
      { key: "phone", label: "Phone", type: "text", section: "Contact" },
      { key: "email", label: "Email", type: "text", section: "Contact" },
      { key: "location_picker", label: "Exact Map Point", type: "locationPicker", section: "Map", width: "full" },
      { key: "photo_url", label: "Branch Photo URL", type: "text", section: "Media", width: "full" },
      { key: "address", label: "Address", type: "textarea", section: "Address", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  team_members: {
    title: "Leadership",
    table: "team_members",
    primaryLabel: "name",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "name", label: "Name", type: "text", required: true, section: "Basics" },
      { key: "designation", label: "Designation", type: "text", required: true, section: "Basics" },
      { key: "location", label: "Where They Are From", type: "text", section: "Basics" },
      { key: "linkedin_url", label: "LinkedIn Profile", type: "text", section: "Profile" },
      { key: "credentials", label: "Credentials", type: "text", section: "Profile" },
      { key: "photo_url", label: "Photo URL", type: "text", section: "Media", width: "full" },
      { key: "excerpt", label: "Card Quote", type: "textarea", section: "Profile", width: "full" },
      { key: "bio", label: "About", type: "textarea", section: "Profile", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
    ],
  },
  senior_management_team: {
    title: "Senior Management Team",
    table: "senior_management_team",
    primaryLabel: "name",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "name", label: "Name", type: "text", required: true, section: "Basics" },
      { key: "designation", label: "Designation", type: "text", required: true, section: "Basics" },
      { key: "photo_url", label: "Photo URL", type: "text", section: "Media", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  insight_categories: {
    title: "Insight Categories",
    table: "insight_categories",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "description", label: "Description", type: "textarea", section: "Content", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  insight_tags: {
    title: "Insight Tags",
    table: "insight_tags",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  menu_items: {
    title: "Mega Menu",
    table: "menu_items",
    primaryLabel: "label",
    fields: [
      { key: "label", label: "Label", type: "text", required: true, section: "Basics" },
      { key: "href", label: "Href", type: "text", required: true, section: "Basics" },
      { key: "group_name", label: "Group", type: "text", required: true, section: "Basics" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  site_settings: {
    title: "Global Settings",
    table: "site_settings",
    primaryLabel: "brand_name",
    fields: [
      { key: "brand_name", label: "Brand Name", type: "text", required: true, section: "Brand" },
      { key: "logo_url", label: "Logo URL", type: "text", section: "Brand" },
      { key: "primary_email", label: "Primary Email", type: "text", section: "Contact" },
      { key: "primary_phone", label: "Primary Phone", type: "text", section: "Contact" },
      { key: "head_office_label", label: "Head Office Label", type: "text", section: "Head Office" },
      { key: "head_office_address", label: "Head Office Address", type: "textarea", section: "Head Office", width: "full" },
      { key: "head_office_map_url", label: "Head Office Map URL", type: "text", section: "Head Office", width: "full" },
      { key: "service_locations_text", label: "Service Locations", type: "textarea", placeholder: "One city per line", section: "Head Office", width: "full" },
      { key: "linkedin_url", label: "LinkedIn URL", type: "text", section: "Social" },
      { key: "instagram_url", label: "Instagram URL", type: "text", section: "Social" },
      { key: "facebook_url", label: "Facebook URL", type: "text", section: "Social" },
      { key: "footer_text", label: "Footer Text", type: "textarea", section: "Footer", width: "full" },
      { key: "disclaimers", label: "Disclaimers", type: "textarea", section: "Footer", width: "full" },
    ],
  },
  newsletter_subscribers: {
    title: "Subscribers",
    table: "newsletter_subscribers",
    primaryLabel: "email",
    readOnly: true,
    listColumns: [
      { key: "email", label: "Email" },
      { key: "status", label: "Status" },
      { key: "source", label: "Source" },
      { key: "created_at", label: "Subscribed On" },
    ],
    fields: [
      { key: "email", label: "Email", type: "text", required: true },
      { key: "status", label: "Status", type: "text", required: true },
      { key: "source", label: "Source", type: "text", required: true },
      { key: "created_at", label: "Subscribed On", type: "datetime", required: true },
    ],
  },
  appointment_slots: {
    title: "Appointment Slots",
    table: "appointment_slots",
    primaryLabel: "appointment_date",
    listColumns: [
      { key: "partner_name", label: "Partner" },
      { key: "location_name", label: "Location" },
      { key: "appointment_date", label: "Date" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        key: "partner_id",
        label: "Partner",
        type: "relation",
        required: true,
        section: "Appointment Details",
        relation: { table: "team_members", valueKey: "id", labelKey: "name", secondaryLabelKey: "designation" },
      },
      {
        key: "location_id",
        label: "Location",
        type: "relation",
        required: true,
        section: "Appointment Details",
        relation: { table: "locations", valueKey: "id", labelKey: "city", secondaryLabelKey: "office_name" },
      },
      { key: "appointment_date", label: "Appointment Date", type: "text", required: true, section: "Timing", placeholder: "YYYY-MM-DD" },
      { key: "start_time", label: "Start Time", type: "text", required: true, section: "Timing", placeholder: "10:00" },
      { key: "end_time", label: "End Time", type: "text", required: true, section: "Timing", placeholder: "11:00" },
      { key: "notes", label: "Notes", type: "textarea", section: "Notes", width: "full" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  appointment_availability_rules: {
    title: "Working Hours",
    table: "appointment_availability_rules",
    primaryLabel: "partner_name",
    density: "compact",
    listColumns: [
      { key: "partner_name", label: "Partner" },
      { key: "location_name", label: "Location" },
      { key: "weekday_labels", label: "Days" },
      { key: "hours_label", label: "Hours" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        key: "partner_id",
        label: "Partner",
        type: "relation",
        required: true,
        section: "Partner & Location",
        relation: { table: "team_members", valueKey: "id", labelKey: "name", secondaryLabelKey: "designation" },
      },
      {
        key: "location_id",
        label: "Location",
        type: "relation",
        required: true,
        section: "Partner & Location",
        relation: { table: "locations", valueKey: "id", labelKey: "city", secondaryLabelKey: "office_name" },
      },
      { key: "enabled_weekdays", label: "Available Days", type: "weekdays", required: true, section: "Weekly Availability" },
      { key: "start_time", label: "Working Start Time", type: "text", required: true, section: "Weekly Availability", placeholder: "10:00" },
      { key: "end_time", label: "Working End Time", type: "text", required: true, section: "Weekly Availability", placeholder: "17:00" },
      { key: "slot_duration_minutes", label: "Slot Duration Minutes", type: "number", required: true, section: "Weekly Availability" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  appointment_blocks: {
    title: "Occupied Blocks",
    table: "appointment_blocks",
    primaryLabel: "block_date",
    density: "compact",
    listColumns: [
      { key: "partner_name", label: "Partner" },
      { key: "location_name", label: "Location" },
      { key: "block_date", label: "Date" },
      { key: "block_label", label: "Blocked Time" },
      { key: "status", label: "Status" },
    ],
    fields: [
      {
        key: "partner_id",
        label: "Partner",
        type: "relation",
        required: true,
        section: "Partner & Location",
        relation: { table: "team_members", valueKey: "id", labelKey: "name", secondaryLabelKey: "designation" },
      },
      {
        key: "location_id",
        label: "Location",
        type: "relation",
        required: true,
        section: "Partner & Location",
        relation: { table: "locations", valueKey: "id", labelKey: "city", secondaryLabelKey: "office_name" },
      },
      { key: "block_date", label: "Blocked Date", type: "text", required: true, section: "Occupied Time", placeholder: "YYYY-MM-DD" },
      { key: "full_day", label: "Block Full Day", type: "checkbox", section: "Occupied Time", width: "full" },
      { key: "start_time", label: "Start Time", type: "text", section: "Occupied Time", placeholder: "14:00" },
      { key: "end_time", label: "End Time", type: "text", section: "Occupied Time", placeholder: "15:30" },
      { key: "note", label: "Note", type: "textarea", section: "Note", width: "full" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  appointment_requests: {
    title: "Appointment Requests",
    table: "appointment_requests",
    primaryLabel: "visitor_name",
    disableCreate: true,
    density: "compact",
    listColumns: [
      { key: "visitor_name", label: "Name" },
      { key: "partner_name", label: "Partner" },
      { key: "location_name", label: "Location" },
      { key: "slot_label", label: "Slot" },
      { key: "visitor_email", label: "Email" },
      { key: "visitor_phone", label: "Phone" },
      { key: "status", label: "Status" },
      { key: "created_at", label: "Requested On" },
    ],
    fields: [
      { key: "slot_id", label: "Manual Slot ID", type: "text", section: "Appointment" },
      { key: "source", label: "Source", type: "text", section: "Appointment" },
      { key: "appointment_date", label: "Appointment Date", type: "text", section: "Appointment" },
      { key: "start_time", label: "Start Time", type: "text", section: "Appointment" },
      { key: "end_time", label: "End Time", type: "text", section: "Appointment" },
      { key: "visitor_name", label: "Name", type: "text", required: true, section: "Visitor" },
      { key: "visitor_email", label: "Email", type: "text", required: true, section: "Visitor" },
      { key: "visitor_phone", label: "Phone", type: "text", required: true, section: "Visitor" },
      { key: "message", label: "Message", type: "textarea", section: "Visitor", width: "full" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Pending", value: "pending" },
          { label: "Confirmed", value: "confirmed" },
          { label: "Cancelled", value: "cancelled" },
        ],
        required: true,
        section: "Review",
      },
    ],
  },
};
