import type { AdminModuleConfig } from "@/types/admin";

const statusOptions = [
  { label: "Draft", value: "draft" },
  { label: "Review", value: "review" },
  { label: "Published", value: "published" },
];

export const adminModules: Record<string, AdminModuleConfig> = {
  pages: {
    title: "Pages",
    table: "pages",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "template_type", label: "Template Type", type: "text", required: true, section: "Basics" },
      { key: "excerpt", label: "Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  practice_areas: {
    title: "Practice Areas",
    table: "practice_areas",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  industry_solutions: {
    title: "Industry Solutions",
    table: "industry_solutions",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  publications: {
    title: "Insights",
    table: "publications",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "image_url", label: "Feature Image URL", type: "text", section: "Media" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "excerpt", label: "Card Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  careers: {
    title: "Careers / Join Us",
    table: "careers",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "excerpt", label: "Listing Excerpt", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "show_apply_cta", label: "Show Apply Button", type: "checkbox", section: "Applications", width: "full" },
      { key: "apply_url", label: "Apply URL", type: "text", section: "Applications", width: "full", placeholder: "https://example.com/apply" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  offices: {
    title: "Offices",
    table: "offices",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "summary", label: "Summary", type: "textarea", section: "Content", width: "full" },
      { key: "body", label: "Body", type: "textarea", section: "Content", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  locations: {
    title: "Locations",
    table: "locations",
    primaryLabel: "city",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Office Basics" },
      { key: "city", label: "City", type: "text", required: true, section: "Office Basics" },
      { key: "office_name", label: "Office Name", type: "text", required: true, section: "Office Basics" },
      { key: "contact_person", label: "Contact Person", type: "text", section: "Office Basics" },
      { key: "phone", label: "Phone", type: "text", section: "Contact" },
      { key: "email", label: "Email", type: "text", section: "Contact" },
      { key: "map_url", label: "Map URL", type: "text", section: "Contact" },
      { key: "address", label: "Address", type: "textarea", required: true, section: "Address", width: "full" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  team_members: {
    title: "Leadership",
    table: "team_members",
    primaryLabel: "name",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "name", label: "Name", type: "text", required: true, section: "Basics" },
      { key: "designation", label: "Designation", type: "text", required: true, section: "Basics" },
      { key: "location", label: "Where They Are From", type: "text", section: "Basics" },
      { key: "linkedin_url", label: "LinkedIn Profile", type: "text", section: "Profile" },
      { key: "credentials", label: "Credentials", type: "text", section: "Profile" },
      { key: "photo_url", label: "Photo URL", type: "text", section: "Media", width: "full" },
      { key: "bio", label: "About", type: "textarea", section: "Profile", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "published_at", label: "Published At", type: "datetime", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
      { key: "featured", label: "Featured", type: "checkbox", section: "Publishing", width: "full" },
    ],
  },
  insight_categories: {
    title: "Insight Categories",
    table: "insight_categories",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "description", label: "Description", type: "textarea", section: "Content", width: "full" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  insight_tags: {
    title: "Insight Tags",
    table: "insight_tags",
    primaryLabel: "title",
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, section: "Basics" },
      { key: "title", label: "Title", type: "text", required: true, section: "Basics" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  menu_items: {
    title: "Mega Menu",
    table: "menu_items",
    primaryLabel: "label",
    fields: [
      { key: "label", label: "Label", type: "text", required: true, section: "Basics" },
      { key: "href", label: "Href", type: "text", required: true, section: "Basics" },
      { key: "group_name", label: "Group", type: "text", required: true, section: "Basics" },
      { key: "display_order", label: "Display Order", type: "number", section: "Publishing" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
    ],
  },
  site_settings: {
    title: "Global Settings",
    table: "site_settings",
    primaryLabel: "brand_name",
    fields: [
      { key: "brand_name", label: "Brand Name", type: "text", required: true, section: "Brand" },
      { key: "logo_url", label: "Logo URL", type: "text", section: "Brand" },
      { key: "primary_email", label: "Primary Email", type: "text", section: "Contact" },
      { key: "primary_phone", label: "Primary Phone", type: "text", section: "Contact" },
      { key: "head_office_label", label: "Head Office Label", type: "text", section: "Head Office" },
      { key: "head_office_address", label: "Head Office Address", type: "textarea", section: "Head Office", width: "full" },
      { key: "service_locations_text", label: "Service Locations", type: "textarea", placeholder: "One city per line", section: "Head Office", width: "full" },
      { key: "linkedin_url", label: "LinkedIn URL", type: "text", section: "Social" },
      { key: "instagram_url", label: "Instagram URL", type: "text", section: "Social" },
      { key: "footer_text", label: "Footer Text", type: "textarea", section: "Footer", width: "full" },
      { key: "disclaimers", label: "Disclaimers", type: "textarea", section: "Footer", width: "full" },
    ],
  },
  newsletter_subscribers: {
    title: "Subscribers",
    table: "newsletter_subscribers",
    primaryLabel: "email",
    readOnly: true,
    listColumns: [
      { key: "email", label: "Email" },
      { key: "status", label: "Status" },
      { key: "source", label: "Source" },
      { key: "created_at", label: "Subscribed On" },
    ],
    fields: [
      { key: "email", label: "Email", type: "text", required: true },
      { key: "status", label: "Status", type: "text", required: true },
      { key: "source", label: "Source", type: "text", required: true },
      { key: "created_at", label: "Subscribed On", type: "datetime", required: true },
    ],
  },
};
